### ISSUE TITLE
Make get_starter_effects and get_dynamic_effects async / parallel requests 

### ISSUE THREAD

**Issue by josh-ashkinaze** [josh-ashkinaze/autocomplete#12]
As of now, we do need to construct character description first. But the starter effects and get_dynamic_effects can be executed in parallel. ANd I think litellm makes this easy. It looks like they have a batch_completion endpt 

https://litellm.vercel.app/docs/completion/batching

**Comment by Weile-Zheng** [comment]
I will look into this
