### ISSUE TITLE
add a timer to the autocomplete app that is x minutes where x is configured in yaml

### ISSUE THREAD

**Issue by josh-ashkinaze** [josh-ashkinaze/autocomplete#17]
- [x] add a timer attribute to the yaml where the attribute has two settings: time in minutes and a string for what string to display when minutes is up 
- [x] add timer to autocomplete app where timer has some circle around it and is displayed in top right and looks aesthetic. It is important that it looks aesthetic!
- [x] at end of timer no need to do anything fancy just do an alert that says the string
- [x] this only kicks in if experiment_mode is set to True

Explanation: For online studies to show people did it they enter a completion code. I am thinking we have people write with this app for X minutes and then they enter completion code that pops up after done....that's why i wanted it to have a string

**Comment by Weile-Zheng** [comment]
Task completed. Please Review. @josh-ashkinaze
